/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

import type Long from 'long';

export class Post {
    id?: Long = undefined;
    userId?: string = undefined;
    content?: string = undefined;
    name?: string = undefined;
    profilePicture?: string = undefined;
    insertDate?: Date = undefined;
    likes: string = '';
    likeCount: number = 0;

    constructor() {
        this.id = undefined;
        this.userId = '';
        this.content = '';
        this.name = undefined;
        this.profilePicture = undefined;
        this.insertDate = undefined;
        this.likes = '[]';
        this.likeCount = 0;
    }

    setId(id: Long): void {
        this.id = id;
    }

    getId(): Long | undefined {
        return this.id;
    }

    setUserId(userId: string): void {
        this.userId = userId;
    }

    getUserId(): string | undefined {
        return this.userId;
    }

    setContent(content: string): void {
        this.content = content;
    }

    getContent(): string | undefined {
        return this.content;
    }

    setName(name: string ): void {
        this.name = name;
    }

    getName(): string | undefined {
        return this.name;
    }

    setProfilePicture(profilePicture: string): void {
        this.profilePicture = profilePicture;
    }

    getProfilePicture(): string | undefined {
        return this.profilePicture;
    }

    setInsertDate(insertDate: Date): void {
        this.insertDate = insertDate;
    }

    getInsertDate(): Date | undefined {
        return this.insertDate;
    }

    setLikes(likes: string): void {
        this.likes = likes;
    }

    getLikes(): string | undefined {
        return this.likes;
    }

    setLikeCount(likeCount: number): void {
        this.likeCount = likeCount;
    }

    getLikeCount(): number {
        return this.likeCount;
    }
}