/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
// import { cloudDatabase } from '@kit.CloudFoundationKit';
//
// class Info extends cloudDatabase.DatabaseObject {
//   public id: number;
//   public uId = 0;
//   public token = '';
//
//   public naturalbase_ClassName(): string {
//     return 'Info';
//   }
// }
//
// export { Info };
class Info {
  id: number
  uId: number
  token: string
  static className: string

  constructor() {
    this.id = undefined;
    this.uId = 0;
    this.token = '';
  }

  setId(id) {
    this.id = id;
  }

  getId() {
    return this.id;
  }

  setuId(uId) {
    this.uId = uId;
  }

  getuId() {
    return this.uId;
  }

  setToken(token) {
    this.token = token;
  }

  getWeight() {
    return this.token;
  }
}

Info.className = 'Info';

export { Info }