/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class yeye {
  id: number
  height: number
  weight: number
  static className: string

  constructor() {
    this.id = undefined;
    this.height = 200;
    this.weight = 300;
  }

  setId(id) {
    this.id = id;
  }

  getId() {
    return this.id;
  }

  setHeight(height) {
    this.height = height;
  }

  getHeight() {
    return this.height;
  }

  setWeight(weight) {
    this.weight = weight;
  }

  getWeight() {
    return this.weight;
  }
}

yeye.className = 'yeye';

export { yeye }

// /*
//  * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
//  * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
//  */
// import { cloudDatabase } from '@kit.CloudFoundationKit';
//
// class yeye extends cloudDatabase.DatabaseObject {
//   public id: number;
//   public height = 200;
//   public weight = 300;
//
//   public naturalbase_ClassName(): string {
//     return 'yeye';
//   }
// }
//
// export { yeye };

